const DEFAULT_TYPE = 'about:blank';

/**
 * Represents a standardized exception response following the RFC 7807 format.
 */
export class ExceptionResponse {
  /** A URI reference that identifies the problem type (default value if not provided). */
  type: string;

  /** A short, human-readable summary of the problem type. */
  title: string;

  /** The HTTP status code generated by the server for this occurrence of the problem. */
  status: number;

  /** A human-readable explanation specific to this occurrence of the problem. */
  detail: string | object;

  /** A URI reference that identifies the specific occurrence of the problem. */
  instance: string;

  /**
   * Creates an instance of `ExceptionResponse`.
   * @param title - A short, human-readable summary of the problem.
   * @param status - The HTTP status code associated with the exception.
   * @param detail - A human-readable explanation of the occurrence of the problem.
   * @param instance - A URI reference identifying the specific occurrence of the problem.
   * @param type - (Optional) A URI reference identifying the problem type. Defaults to `DEFAULT_TYPE`.
   */
  constructor(
    title: string,
    status: number,
    detail: string | object,
    instance: string,
    type?: string,
  ) {
    this.type = type ?? DEFAULT_TYPE;
    this.title = title;
    this.status = status;
    this.detail = detail;
    this.instance = instance;
  }
}
